---
- name: Remove Iteration_2 Nodes from Traefik Load Balancer
  hosts: traefik
  become: yes
  gather_facts: false
  vars:
    - ansible_ssh_user: ubuntu
  vars_files:
    - ../vars/linux.yaml
  tasks:

  # ------------------------------------------------------------------------
  # Disable the `iteration_2` PSNs in the Load Balancer
  # ------------------------------------------------------------------------

    - name: Copy Configuration to LB disabling `iteration_2` nodes
      ansible.builtin.copy:
        src: radius_2.yaml
        dest: /etc/traefik/config/
        backup: no

    - name: Rename the `radius_2.yaml` file to `radius.yaml`
      ansible.builtin.shell:
        cmd: sudo mv radius_2.yaml radius.yaml
        chdir: /etc/traefik/config/
