---
- name: Restore PSNs to the Traefik Load Balancer
  hosts: traefik
  become: yes
  gather_facts: false
  vars:
    - ansible_ssh_user: ubuntu
  vars_files:
    - ../vars/linux.yaml
  tasks:

  # ------------------------------------------------------------------------
  # Restore the original RADIUS configuration in the Load Balancer
  # ------------------------------------------------------------------------

    - name: Restore all PSNs in the Load Balancer
      copy:
        src: radius_og.yaml
        dest: /etc/traefik/config/
        backup: no

    - name: Rename the `radius_og.yaml` file to `radius.yaml`
      ansible.builtin.shell:
        cmd: sudo mv radius_og.yaml radius.yaml
        chdir: /etc/traefik/config/
