---

- name: Get Shape Facts
  hosts: localhost
  collections:
    - oracle.oci
  vars_files:
    - vars/main.yaml
    
  tasks:
  - name: List shapes
    oci_compute_shape_facts:
      # required
      compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT') }}"