---
- name: Reset ISE GUI Password
  hosts: vmware-sadmin
  connection: ansible.netcommon.network_cli
  gather_facts: no
  vars_files:
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/main.yaml
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_ssh_user: "{{ lookup('env','ISE_REST_USERNAME') }}"

  tasks:

- name: Restore ISE Configuration | {{ ise_restore_filename }}
  delegate_to: localhost
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v1/backup-restore/config/restore"
    method: POST
    url_username: "{{ ise_username }}"
    url_password: "{{ ise_password }}"
    force_basic_auth: yes
    force: true # do not get a cached copy
    follow_redirects: safe
    body_format: json
    body: |
      {
        "repositoryName": "{{ ise_repository_name }}",
        "backupEncryptionKey": "{{ ise_backup_encryption_key }}",
        "restoreFile": "{{ ise_restore_filename }}",
        "restoreIncludeAdeos": "{{ ise_restore_adeos }}"
      }
    status_code: [
                  202, # Config DB restore task initiated
                  400, # Invalid Input: Invalid repository name, etc.
                  401, # Unauthorized
                  405, # A backup or restore is already in progress
                  ]
    timeout: 600 # in seconds (10 minutes)
    validate_certs: "{{ ise_verify }}"
    return_content: true
  register: ise_restore_status
  failed_when: ise_restore_status.status != 202
  ignore_errors: true # Errors do not stop execution 