---
- name: The second Iteration of Cloud PSN Upgrades is Complete!
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

  tasks:

    - name: Send Email Notification
      ansible.builtin.shell:
        cmd: "ssmtp charlie@isedemolab.com < ../notifications/33_iteration2_done.txt"
    
    - name: Iteration 2 is Complete!! 🤍
      ansible.builtin.debug:
        msg: |
           
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣶
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣯⣿
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣯⣯⣯⣿
           ⠀⠀⠀⠀⠀⠀⠀⢀⣤⡶⠀⠀⠀⢠⣿⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⢴⣤
           ⠀⠀⠀⠀⠀⢀⣴⠟⠀⠀⠀⠀⢠⣿⣯⣯⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⠈⢻⣦
           ⠀⠀⠀⠀⢠⣿⠁⠀⠀⠀⠀⢀⣿⣯⣯⣯⣯⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⠀⠈⣿⡀
           ⠀⠀⠀⢠⣿⠀⠀⠀⠀⠀⢀⣿⣯⣯⣯⣯⠟⠛⢿⣯⣯⣯⣯⣿⠀⠀⠀⠀⠀⠀⣿
           ⠀⠀⠀⣿⠁⠀⠀⠀⠀⢀⣿⣯⣯⠛⠁⠀⠀⠀⠀⠀⠉⠛⣿⣯⣿⠀⠀⠀⠀⠀⢸⣧  Iteration 2 complete!
           ⠀⠀⠀⣿⠀⠀⠀⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⣿
           ⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣶⠀⢀⣴⠶⠒⠶⣤⠀⠀⣶⠶⠶⠶⠶⠀⠀⠀⠀⠀⢀⣿  Move on to the final stage
           ⠀⠀⠀⢻⣆⠀⠀⠀⠀⠀⣿⠀⠘⣧⣀⠀⠀⠈⠁⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠏
           ⠀⠀⠀⠀⢿⣄⠀⠀⠀⠀⣿⠀⠀⠀⠀⠉⠙⢷⡀⠀⣿⠉⠉⠉⠉⠀⠀⠀⠀⣰⡟   (admin_2/)
           ⠀⠀⠀⠀⠀⢻⣦⠀⠀⠀⣿⠀⠙⣦⣀⣀⣀⣼⠁⠀⣿⣀⣀⣀⣀⠀⠀⠀⣼⠋
           ⠀⠀⠀⠀⠀⠀⠈⢿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⠟⠉
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠛⠛⠛⠋⠉⠁
           
           