---
- name: Remove Nodes from ISE Deployment & add Roles and Services to PPAN
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/main.yaml
    - ../../vars/banners.yaml
  tasks:

  # ------------------------------------------------------------------------
  # Remove the three PSNs that will be "upgraded" in iteration 2
  # ------------------------------------------------------------------------

    - name: Remove ISE Node from the Deployment | azure-psn2 🪓 | 🕑 ~3m
      cisco.ise.node_deployment:
        ise_hostname: "{{ upg_ppan }}" # ISE PAN
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_debug: "{{ ise_debug }}"
        state: absent
        hostname: azure-psn2 # MUST use the hostname here, fqdn will fail!
      register: ise_node_update
      timeout: 600 # Default: 300. Stop checking after <seconds>
      ignore_errors: yes

    - name: Remove ISE Node from the Deployment | oci-psn2 🪓 | 🕑 ~3m
      cisco.ise.node_deployment:
        ise_hostname: "{{ upg_ppan }}" # ISE PAN
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_debug: "{{ ise_debug }}"
        state: absent
        hostname: oci-psn2 # MUST use the hostname here, fqdn will fail!
      register: ise_node_update
      timeout: 600 # Default: 300. Stop checking after <seconds>
      ignore_errors: yes

    - name: Remove ISE Node from the Deployment | aws-psn2 🪓 | 🕑 ~3m
      cisco.ise.node_deployment:
        ise_hostname: "{{ upg_ppan }}" # ISE PAN
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_debug: "{{ ise_debug }}"
        state: absent
        hostname: aws-psn2 # MUST use the hostname here, fqdn will fail!
      register: ise_node_update
      timeout: 600 # Default: 300. Stop checking after <seconds>
      ignore_errors: yes

    - name: Verify All Nodes Deregistered from PPAN | {{ upg_ppan }}
      # when: inventory_hostname == ise_ppan_name
      cisco.ise.node_info:
        ise_hostname: "{{ upg_ppan }}" # PPAN!
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_debug: "{{ ise_debug }}"
      register: node_info
      until: node_info.ise_response | count == 1
      delay: 10 # Default: 0. seconds to delay between retries
      retries: 180
      timeout: 1800 # retries * delay. Default: 300. Stop checking after <seconds>

