---

- name: Create an ISE 3.3 PSN in OCI
  gather_facts: false
  hosts: localhost
  collections:
    - oracle.oci
  vars_files:
    - ../../vars/main.yaml
    - ../../vars/banners.yaml

##################################################################################
# Use the `OCI Stuff` section of the `vars/main.yaml` file to add ISE specific
# information for OCI including the `OCID` for the ISE installation inage for the 
# desired version, the shape to be used, etc.
# 
# The HDD size is set with the `boot_volume_size_in_gbs` option under 
# `source_details`, the CPU and RAM are set under `shape_config`.  Remember
# that 1 OCPU = 2 vCPU
#
# The `user_data` must be base64 encoded to be used
##################################################################################
  tasks:
    - name: Create oci-psn2 ⏳
      oci_compute_instance:
        availability_domain: "{{ oci_ad }}"
        compartment_id: "{{ instance_compartment }}"
        name: "oci-psn2"
        source_details:
          source_type: image
          image_id: "{{ ise33_image }}"
          boot_volume_size_in_gbs: "300"
        shape: "{{ psn_shape }}"
        shape_config:
          memory_in_gbs: "16"
          ocpus: "2"
        create_vnic_details:
          assign_public_ip: False
          display_name: "System NIC"
          private_ip: "192.168.102.111"
          hostname_label: "oci-psn2"
          subnet_id: "{{ lookup('env', 'SUBNET_ID') }}"
        metadata:
            ssh_authorized_keys: "{{ lookup('file',  ssh_key_public_file) }}"
            user_data: "aG9zdG5hbWU9b2NpLXBzbjIKcHJpbWFyeW5hbWVzZXJ2ZXI9MTAuMS4xMDAuMTAKZG5zZG9tYWluPXNlY3VyaXR5ZGVtby5uZXQKbnRwc2VydmVyPTEwLjEuMTAwLjEKdGltZXpvbmU9QW1lcmljYS9OZXdfWW9yawpwYXNzd29yZD1JU0Vpc0MwMExJU0UKZXJzYXBpPXllcwpvcGVuYXBpPXllcwpweEdyaWQ9eWVzCnB4Z3JpZF9jbG91ZD15ZXM="
        freeform_tags:
            project: "{{ project_name }}"
            owner: "{{ owner }}"
            started: "{{ '%Y-%m-%d T%H:%M:%S-%Z' | strftime }}"
            role: "PSN"
            version: "3.3"

    - name: Create oci-psn2 ⏳
      oci_compute_instance:
        availability_domain: "{{ oci_ad }}"
        compartment_id: "{{ instance_compartment }}"
        name: "oci-psn4"
        source_details:
          source_type: image
          image_id: "{{ ise33_image }}"
          boot_volume_size_in_gbs: "300"
        shape: "{{ psn_shape }}"
        shape_config:
          memory_in_gbs: "16"
          ocpus: "2"
        create_vnic_details:
          assign_public_ip: False
          display_name: "System NIC"
          private_ip: "192.168.102.113"
          hostname_label: "oci-psn4"
          subnet_id: "{{ lookup('env', 'SUBNET_ID') }}"
        metadata:
            ssh_authorized_keys: "{{ lookup('file',  ssh_key_public_file) }}"
            user_data: "aG9zdG5hbWU9b2NpLXBzbjQKcHJpbWFyeW5hbWVzZXJ2ZXI9MTAuMS4xMDAuMTAKZG5zZG9tYWluPXNlY3VyaXR5ZGVtby5uZXQKbnRwc2VydmVyPTEwLjEuMTAwLjEKdGltZXpvbmU9QW1lcmljYS9OZXdfWW9yawpwYXNzd29yZD1JU0Vpc0MwMExJU0UKZXJzYXBpPXllcwpvcGVuYXBpPXllcwpweEdyaWQ9eWVzCnB4Z3JpZF9jbG91ZD15ZXM="
        freeform_tags:
            project: "{{ project_name }}"
            owner: "{{ owner }}"
            started: "{{ '%Y-%m-%d T%H:%M:%S-%Z' | strftime }}"
            role: "PSN"
            version: "3.3"

    - name: oci-psn2 has been deployed!
      ansible.builtin.debug:
        msg: |
          {{bar}}        ,,gggggggggggggggggggg,,        
          {{bar}}    ,g@$$$$$$$$$$$$$$$$$$$$$$$$$$@g,    
          {{bar}}  ,@$$$$$F*""``````````````""*%$$$$$@,  
          {{bar}} /$$$$@`                         %$$$$k 
          {{bar}},$$$$F                            ]$$$$k
          {{bar}}$$$$$                              $$$$$
          {{bar}}%$$$$                              #$$$$
          {{bar}}]$$$$k                            ,$$$$F
          {{bar}} ]$$$$k                          g$$$$F 
          {{bar}}  '$$$$$@g,,                ,,g@$$$$$"  
          {{bar}}    "%$$$$$$$$$$$$$$$$$$$$$$$$$$$$@"    
          {{bar}}       `"*R%%%%%%%%%%%%%%%%%%R*"` 

    - name: Refresh inventory to ensure new instances exist in inventory ⟳
      ansible.builtin.meta: refresh_inventory