---
- name: Wait for ISE login to be available (Application Server) ⏳
  gather_facts: no
  hosts: localhost
  vars_files:
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/main.yaml
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/banners.yaml

  tasks:

    - name: Wait for ISE App Server to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait ~25 minutes for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on ise-azure
            (::::)
           --------

    - name: ISE Login ⮕ | ise-azure ⏳
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://ise-azure.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks

    - name: Wait for ISE App Server to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait ~25 minutes for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on ise-azure2
            (::::)
           --------

    - name: ISE Login ⮕ | ise-azure2 ⏳
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://ise-azure2.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks
