---
- name: Configure FTP Repository on ISE node
  gather_facts: no
  hosts: localhost
  vars_files:
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/main.yaml

  tasks:
   
  # ------------------------------------------------------------------------
  # Create a repository from which you copy the public key file.
  # CDROM and DISK repositories do not use the `userName` or `password`
  # fields for the repository as shown in the DISK repository example.
  # Supported Repository Types are:
  # - CDROM
  # - DISK
  # - FTP
  # - HTTP
  # - HTTPS
  # - NFS
  # - SFTP
  # - TFTP
  # ------------------------------------------------------------------------

    # - name: Create DISK Repository in ISE
    #   cisco.ise.repository:
    #     ise_hostname: "{{ ise_ppan }}"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #     state: present
    #     enablePki: false
    #     name: ssh
    #     # password: string # Not used for Disk repository
    #     path: /
    #     protocol: DISK
    #     # serverName: string # Not used for Disk repository
    #     # userName: string # Not used for Disk repository

    - name: Create FTP Repository in ISE
      cisco.ise.repository:
        ise_hostname: "ise-azure.securitydemo.net" # FQDN or IP Address
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        enablePki: false
        name: FTP
        password: "{{ repo_password }}"
        path: /
        protocol: FTP
        serverName: 10.1.100.6 # FQDN or IP Address
        userName: "{{ repo_user }}" 

    - name: Create FTP Repository in ISE
      cisco.ise.repository:
        ise_hostname: "ise-azure2.securitydemo.net" # FQDN or IP Address
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        enablePki: false
        name: FTP
        password: "{{ repo_password }}"
        path: /
        protocol: FTP
        serverName: 10.1.100.6 # FQDN or IP Address
        userName: "{{ repo_user }}" 
