---
- name: Install ISE Patch
  gather_facts: no
  hosts: localhost
  # connection: local
  vars_files:
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/main.yaml
    - ~/Upgrade_ISE_in_Hybrid_Cloud/vars/banners.yaml

  tasks:
  
  - name: Install 3.2 Patch 3 on ise-azure
    cisco.ise.patch_install:
      ise_hostname: "ise-azure.securitydemo.net"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      patchName: "ise-patchbundle-3.2.0.542-Patch3-23071904.SPA.x86_64.tar.gz"
      repositoryName: FTP

  - name: Install 3.2 Patch 3 on ise-azure2
    cisco.ise.patch_install:
      ise_hostname: "ise-azure2.securitydemo.net"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      patchName: "ise-patchbundle-3.2.0.542-Patch3-23071904.SPA.x86_64.tar.gz"
      repositoryName: FTP

  - name: Patch Installation Initialized
    ansible.builtin.debug:
      msg: |
         
         
                            ▓▓ 
                           ▓╣╣▓ 
                          ▓╣╣╣╣▓ 
                         ▓╣╣╣╣╣╣▓       
                ,▄█     ▓╣╣╣╣╣╣╣╣▓     ▀█▄
              ,█▀      ▓╣╣╣╣╣╣╣╣╣╣▓      ▀█▄
             ▄█'      ▓╣╣╣╣╣╣╣╣╣╣╣╣▓       ██
            ▄█       ▓╣╣╣╣╣╣▓▓╣╣╣╣╣╣▓       ▀█
           ]█       ▓╣╣╣╣▓╜    ╙▓╣╣╣╣▓       █▌
           █▌      ▓╣▓╜            ╙▓╣▓      ▐█   Patch installation has been initiated
           █▌                                 █▌
           █▌                                 █▌  Be patient as the patch installs and the
           ▐█                                ▐█   ISE node(s) restart
            █▌                              ,█ 
             █▄                            ,█
              ▀█▄                         ▄█
                ▀█▄                    ,▄█▀
                  ▀█▄▄              ▄▄█▀╜
                     ▀▀▀██▄▄▄▄▄▄██▀▀▀
         
         

  - name: 🛑 Pause for 3 Minutes to Upload Patch and Start Installation 🛑
    ansible.builtin.pause:
      seconds: 180
  
  - name: Wait for ⬇ Reboot⬆
    delegate_to: localhost
    vars:
      wait_timeout: "{{ 30 * 60 }}" # 1800s == 30 minutes per port
    with_items:
      - 443 # SSH/REST/API Gateway
      - 80 # Admin UI redirect to 443
      - 22 # SSH
    ansible.builtin.wait_for:
      host: "ise-azure2.securitydemo.net"
      port: "{{ item }}"
      state: stopped # Port is CLOSED
      sleep: 3 # Default: 1. Seconds to sleep between checks. 💡 10 seconds is not fast enough to catch SSH???
      timeout: "{{ wait_timeout }}" # Default: 300. Stop checking after <seconds>
    ignore_errors: yes # Errors do not stop execution