---
- name: install AI Profiles for ISE Proposals
  hosts: ipsk
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ansible_ssh_user: "{{ ise_username }}"
    ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"
  vars_files:
    - ../vars/linux.yaml

  tasks:

    - name: Create SpaTools folder
      ansible.builtin.shell:
        cmd: mkdir SpaTools
      ignore_errors: yes

    - name: Download SPA Tools Probe Package
      ansible.builtin.get_url:
        url: https://isedemolab.com/endpoints/spa_tools_probe.tar
        dest: /home/iseadmin/SpaTools/

    - name: Load Spa Tools into Docker
      ansible.builtin.shell:
        cmd: docker load < /home/iseadmin/SpaTools/spa_tools_probe.tar

    - name: Tag the Docker Image
      ansible.builtin.shell:
        cmd: docker tag 41a03b7bdb6b probes:0.1.2

    - name: Start the probes container and set the IP address for Spa Tools
      ansible.builtin.shell:
        cmd: "{{ spa_tools_ip }}"
      ignore_errors: yes

    - name: Download SPA Tools Probes files
      ansible.builtin.get_url:
        url: https://isedemolab.com/endpoints/probes/probes.zip
        dest: /home/iseadmin/SpaTools/

    - name: Unzip the probes files
      ansible.builtin.shell:
        cmd: unzip /home/iseadmin/SpaTools/probes.zip -d /home/iseadmin/SpaTools/
      ignore_errors: yes

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/apple.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/asus.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/google.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/lexmark.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/microsoft.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/rpi.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/samsung.sh

    - name: Make the script executable
      ansible.builtin.shell:
        cmd: chmod 755 /home/iseadmin/SpaTools/sony.sh