---
- name: install AI Profiles for ISE Proposals
  hosts: ipsk
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ansible_ssh_user: "{{ ise_username }}"
    ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"
  vars_files:
    - ../vars/linux.yaml

  tasks:

    - name: Run the probes script for Apple endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/apple.sh

    - name: Run the probes script for ASUS endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/asus.sh

    - name: Run the probes script for Google endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/google.sh

    - name: Run the probes script for Lexmark endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/lexmark.sh

    - name: Run the probes script for Microsoft endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/microsoft.sh

    - name: Run the probes script for Raspberry Pi endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/rpi.sh

    - name: Run the probes script for Samsung endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/samsung.sh

    - name: Run the probes script for Sony endpoints
      ansible.builtin.script: /home/iseadmin/SpaTools/sony.sh
