---
- name: Remove Nodes from ISE Deployment & add Roles and Services to PPAN
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml
  tasks:

  # ------------------------------------------------------------------------
  # Remove the three PSNs that will be "upgraded" in iteration 1
  # ------------------------------------------------------------------------

  - name: Remove ISE Node from the Deployment | azure-psn 🪓 | 🕑 ~3m
    cisco.ise.node_deployment:
      ise_hostname: "{{ upg_ppan }}" # ISE PAN
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      ise_debug: "{{ ise_debug }}"
      ise_uses_api_gateway: true
      state: absent
      hostname: azure-psn # MUST use the hostname here, fqdn will fail!
    register: ise_node_update
    timeout: 600 # Default: 300. Stop checking after <seconds>
    ignore_errors: yes

  # ------------------------------------------------------------------------
  # It's not unusual to receive an error for each node that is deregistered.
  # The error will contain syntax similar to:
  #
  # An exception occurred during task execution. To see the full traceback, use -vvv. The error was: }
  # fatal: [localhost]: FAILED! => changed=false
  #   msg: |-
  #     An error occured when executing operation. The error was: [500] - The server could not fulfill the request.
  #    {
  #      "error" : {
  #        "message" : "Internal Error - Exception occurred: java.rmi.RemoteException: null; nested exception is: \n\tjava.lang.NullPointerException"
  #      },
  #      "version" : "1.0.0"
  #    }
  # ...ignoring
  #
  # OR
  #
  # An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ciscoisesdk.exceptions.ciscoisesdkException: Socket error HTTPSConnectionPool(host='vmware-admin.securitydemo.net', port=443): Read timed out. (read timeout=60)
  # fatal: [localhost]: FAILED! => changed=false
  #   msg: 'An error occured when executing operation. The error was: Socket error HTTPSConnectionPool(host=''vmware-admin.securitydemo.net'', port=443): Read timed out. (read timeout=60)'
  # ...ignoring
  #
  # OR
  #
  # An exception occurred during task execution. To see the full traceback, use -vvv. The error was: }
  # fatal: [localhost]: FAILED! => changed=false
  #   msg: |-
  #     An error occured when executing operation. The error was: [500] - The server could not fulfill the request.
  #     {
  #       "error" : {
  #         "message" : "Internal Error - ConnectionException occurred: java.net.ConnectException: NOTE: the following deregistered node(s) are not currently reachable: azure-psn. Be sure to reset the configuration on these nodes manually, as they may not revert to Standalone on their own."
  #       },
  #       "version" : "1.0.0"
  #     }
  # ...ignoring
  #
  #
  # These errors can be ignored, as the node(s) will actually be successfully deregistered.
  # This is why we use the `ignore_errors: yes` flag.
  # ------------------------------------------------------------------------

  - name: Remove ISE Node from the Deployment | oci-psn 🪓 | 🕑 ~3m
    cisco.ise.node_deployment:
      ise_hostname: "{{ upg_ppan }}" # ISE PAN
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      ise_debug: "{{ ise_debug }}"
      ise_uses_api_gateway: true
      state: absent
      hostname: oci-psn # MUST use the hostname here, fqdn will fail!
    register: ise_node_update
    timeout: 600 # Default: 300. Stop checking after <seconds>
    ignore_errors: yes

  - name: Remove ISE Node from the Deployment | aws-psn 🪓 | 🕑 ~3m
    cisco.ise.node_deployment:
      ise_hostname: "{{ upg_ppan }}" # ISE PAN
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      ise_debug: "{{ ise_debug }}"
      ise_uses_api_gateway: true
      state: absent
      hostname: aws-psn # MUST use the hostname here, fqdn will fail!
    register: ise_node_update
    timeout: 600 # Default: 300. Stop checking after <seconds>
    ignore_errors: yes

  - name: Verify All Nodes Deregistered from PPAN | {{ upg_ppan }}
    # when: inventory_hostname == ise_ppan_name
    cisco.ise.node_info:
      ise_hostname: "{{ upg_ppan }}" # PPAN!
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      ise_debug: "{{ ise_debug }}"
    register: node_info
    until: node_info.ise_response | count == 4  # Back to pre-webinar deployment!
    delay: 10 # Default: 0. seconds to delay between retries
    retries: 180
    timeout: 1800 # retries * delay. Default: 300. Stop checking after <seconds>

