---
- name: Create the Primary Admin Node in VMware
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

#--------------------------------------------------------------------------
# This playbook Deploy ISE to an ESXi Host, attach the ztp.iso, and
# power on the VM
#--------------------------------------------------------------------------

  tasks:

    - name: Deploy {{ upg_ppan }} version 3.3 on ESXi
      community.vmware.vmware_guest:
        name: vmware-admin
        state: poweredoff
        datastore: "{{ datastore }}"
        guest_id: rhel8_64Guest
        folder: /
        disk:
        - size_gb: 300
          type: thin
          controller_number: 0
          unit_number: 0
          controller_type: paravirtual
          datastore: "[{{ datastore }}]"
          disk_mode: persistent
        networks: 
        - name: '{{ ProvisioningNetworkLabel }}'
        cdrom:
        - type: "iso"
          iso_path: "[{{ iso_datastore }}] /{{ ise33_iso }}"
          controller_number: 0
          unit_number: 0
        - type: "iso"
          iso_path: "[{{ datastore }}] /ISO/ZTP/vmware-admin.iso"
          controller_number: 1
          unit_number: 0
        hardware:
          boot_firmware: "bios"
          memory_mb: 32768
          num_cpus: 16
          num_cpu_cores_per_socket: 4
          cpu_reservation: 32000
          mem_reservation: 32768
          memory_reservation_lock: true
          scsi: paravirtual
          version: latest
        validate_certs: no
      delegate_to: localhost
      register: deploy_vm
      ignore_errors: yes

    #--------------------------------------------------------------------------
    # Power on the VM
    #--------------------------------------------------------------------------

    - name: Power on virtual machine
      community.vmware.vmware_guest_powerstate:
        validate_certs: false
        name: vmware-admin
        state: powered-on

    - name: Your Primary Admin Node has been deployed!
      ansible.builtin.debug:
        msg: |
          {{bar}}(@@,     g@@@@g,g@@@@g,g@@@@g  @k     g@      @F g@@%%@g,   @L,g@@  ,g@NNBw  
          {{bar}} $@@    g@@P`@@@P``]@@@P``]@@@ '@C   ,@]@    #@         $K  @@P    @P     '@w 
          {{bar}}  $@@  g@@P  @@@    @@@    @@@  ]@   @` ]@  /@   gg%NN%m@@  @$    ]@ggggggg#@   
          {{bar}}   $@@g@@P   @@@    @@@    @@@   ]@ @F   $k,@`  @F      [@  @F    ]@            
          {{bar}}    $@@@P    @@@    @@@    @@@    $@@     @@F   %@,   ,g$@  @F     "$g,  ,g@    
          {{bar}}     ""`      "`    `"`    '"`     "       `      """"  '`  "         """"  
          {{bar}}
          {{bar}}                Your Primary Admin Node has been deployed!
          
    - name: Refresh inventory to ensure new instances exist in inventory ⟳
      ansible.builtin.meta: refresh_inventory

    - name: Wait for ISE App Server on Primary Admin Node to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on vmware-admin
            (::::)
           --------

    - name: ISE Login ⮕ | vmware-admin
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://vmware-admin.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks