---
- name: Import certificates into ISE
  gather_facts: false
  hosts: localhost
  # connection: local
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml
    - ../.cert/ise_certs.yaml

  tasks:
    #----------------------------------------------------------------------------
    # 🛈 The `data`and `privateKeyData` fields require the plain-text 
    # contents of the certificate file. Every space needs to be 
    # replaced with a newline escape sequence (\n) character.
    #
    # In your *nix terminal, use the command
    # awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' <<your pem file>>
    # to automatically format your .pem certificates and .pvk 
    # private key files to be read by ISE.
    #
    # ⚠ The CA Cert chain MUST be imported before you can import the 
    # system certificate.
    #----------------------------------------------------------------------------

    # - name: Import Hydrant CA Cert to Trusted Cert Store on vmware-admin
    #   cisco.ise.trusted_certificate_import:
    #     ise_hostname: "vmware-admin.securitydemo.net"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #     allowBasicConstraintCAFalse: true
    #     allowOutOfDateCert: true
    #     allowSHA1Certificates: true
    #     data: "{{ ca_cert }}"
    #     description: string
    #     name: HydrantID Server CA O1
    #     trustForCertificateBasedAdminAuth: true
    #     trustForCiscoServicesAuth: true
    #     trustForClientAuth: true
    #     trustForIseAuth: true
    #     validateCertificateExtensions: true

    - name: Import securitydemo.net system certificate on vmware-admin
      cisco.ise.system_certificate_import:
        ise_hostname: "vmware-admin.securitydemo.net"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        admin: "true"
        allowExtendedValidity: "false"
        allowOutOfDateCert: "false"
        allowPortalTagTransferForSameSubject: "true"
        allowReplacementOfCertificates: "true"
        allowReplacementOfPortalGroupTag: "true"
        allowRoleTransferForSameSubject: "true"
        allowSHA1Certificates: "false"
        allowWildCardCertificates: "true"
        data: "{{ certificate }}"
        eap: "false"
        ims: "false"
        name: securitydemo.net
        password: "{{ pvk_password }}"
        portal: "true"
        portalGroupTag: "Default Portal Certificate Group"
        privateKeyData: "{{ private_key }}"
        pxgrid: "false"
        radius: "false"
        saml: "false"
        validateCertificateExtensions: "false"

    - name: 🛑 Pause for 1 Minute to for Services to Stop 🛑
      ansible.builtin.pause:
        seconds: 60
        
    - name: Wait for ISE App Server on Primary Admin Node to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on vmware-admin
            (::::)
           --------

    - name: ISE Login ⮕ | vmware-admin
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://vmware-admin.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks