---
- name: The ISE Deployment Upgrade is Complete!
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

  tasks:

    - name: Send Email Notification
      ansible.builtin.shell:
        cmd: "ssmtp charlie@isedemolab.com < ../notifications/33_deployment_done.txt"

    - name: Your deployment has been upgraded to 3.3! 🤍
      ansible.builtin.debug:
        msg: |
           
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣄
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣯⣯⣯⣄
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣯⣯⣯⣯⣯⣄⠀⠀⠀⠀⠀⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣀
           ⠀⠀⠀⠀⣤⡿⠋⠀⠀⠀⣴⣯⣯⣯⣯⣯⣯⣯⣄⠀⠀⠀⠛⣷⣌⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄⠀⠀⠀⠀⠀
           ⠀⠀⣠⡿⠉⠀⠀⠀⠀⣴⣯⣯⣯⣯⣯⣯⣯⣯⣯⣄⠀⠀⠀⠀⠙⣷⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀⠀
           ⠀⣴⠏⠀⠀⠀⠀⠀⣰⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣄⠀⠀⠀⠀⠀⢿⣄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀
           ⣰⡟⠀⠀⠀⠀⠀⣰⣯⣯⣯⣯⠛⠉⠀⠙⠻⣯⣯⣯⣯⡀⠀⠀⠀⠀⠀⣿⡈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄
           ⣿⠀⠀⠀⠀⠀⢰⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⢿⣯⠀⠀⠀⠀⠀⢸⣧⣿⣿⠀⣿⠉⣤⣤⣿⡇⢠⣤⣼⣿⣿⠀⢠⣤⡀⠙⣿⣿⠿⣿⣿⠿⣿⠿⣿⠿⣿⣿⣿⠿⢿⣿⣿⣿⠀⢸⣿⣿⣿⠿⢿⣿⡇⢸⠿⢿⣿⣿
           ⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⢸⣿⠀⣿⣶⣤⠀⢻⡇⢠⣤⣼⣿⣿⠀⢸⣿⡟⠀⣏⢀⣋⣀⣿⠀⣾⡄⢰⣷⠀⣟⠀⣿⡆⠈⣿⣿⠀⢸⣿⣿⠛⣉⠀⢸⡇⢰⣿⠀⢹⣿
           ⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡏⣿⣿⣤⣿⣤⣤⣤⣿⣧⣤⣤⣤⣿⣿⣤⣤⣤⣴⣿⣿⣦⣤⣤⣿⣤⣿⣧⣼⣿⣤⣿⣦⣤⣤⣿⣿⣿⣤⣤⣤⣼⣦⣤⣦⣼⣧⣴⣤⣴⣿⡟
           ⠘⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
           ⠀⠙⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⢡⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀
           ⠀⠀⠈⢿⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠟⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠉⠀⠀⠀
           ⠀⠀⠀⠀⠉⠻⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⠛⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀⠀⠀⠀
           ⠀⠀⠀⠀⠀⠀⠀⠉⠛⠷⣶⣤⣤⣤⣤⣤⣤⣴⣶⠟⠋⠉
           
           
                         The ISE Deployment is now UPGRADED to version 3.3!        
