---
- name: Create the Admin Nodes in VMware
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

#--------------------------------------------------------------------------
# This playbook will Deploy ISE to an ESXi Host, attach the ztp.iso, and
# power on the VM
#--------------------------------------------------------------------------

  tasks:

    #--------------------------------------------------------------------------
    # The example shown here is to install to an ESXi host, you can
    # install to vCenter Server as well.
    # The entries shown below are the minimum required entries.
    #--------------------------------------------------------------------------
    # Zero Touch Provisioning (ZTP)
    #--------------------------------------------------------------------------
    # Attach the ztp.iso to the VM using the full datastore path
    # the `datastore` name must be enclosed in [brackets] followed by
    # the rest of the path.
    # Specify the device to attach the iso: `cdrom`, `controller_number`,
    # `unit_number`
    #--------------------------------------------------------------------------

    - name: Deploy {{ upg_ppan }} on ESXi
      community.vmware.vmware_guest:
        name: vmware-admin
        state: poweredoff
        datastore: "{{ datastore }}"
        guest_id: rhel8_64Guest
        folder: /
        disk:
        - size_gb: 300
          type: thin
          controller_number: 0
          unit_number: 0
          controller_type: paravirtual
          datastore: "[{{ datastore }}]"
          disk_mode: persistent
        networks: 
        - name: '{{ ProvisioningNetworkLabel }}'
        cdrom:
        - type: "iso"
          iso_path: "[{{ iso_datastore }}] /{{ ise32_iso }}"
          controller_number: 0
          unit_number: 0
        - type: "iso"
          iso_path: "[{{ datastore }}] /ISO/ZTP/vmware-admin.iso"
          controller_number: 1
          unit_number: 0
        hardware:
          boot_firmware: "bios"
          memory_mb: 32768
          num_cpus: 8
          num_cpu_cores_per_socket: 4
          cpu_reservation: 16000
          mem_reservation: 32768
          memory_reservation_lock: true
          scsi: paravirtual
          version: latest
        validate_certs: no
      delegate_to: localhost
      register: deploy_vm
      ignore_errors: yes

    #--------------------------------------------------------------------------
    # Power on the VM
    #--------------------------------------------------------------------------

    - name: Power on virtual machine
      community.vmware.vmware_guest_powerstate:
        validate_certs: false
        name: vmware-admin
        state: powered-on

    - name: Deploy {{ upg_span }} on ESXi
      community.vmware.vmware_guest:
        name: vmware-sadmin
        state: poweredoff
        datastore: "{{ datastore }}"
        guest_id: rhel8_64Guest
        folder: /
        disk:
        - size_gb: 300
          type: thin
          controller_number: 0
          unit_number: 0
          controller_type: paravirtual
          datastore: "[{{ datastore }}]"
          disk_mode: persistent
        networks: 
        - name: '{{ ProvisioningNetworkLabel }}'
        cdrom:
        - type: "iso"
          iso_path: "[{{ iso_datastore }}] /{{ ise32_iso }}"
          controller_number: 0
          unit_number: 0
        - type: "iso"
          iso_path: "[{{ datastore }}] /ISO/ZTP/vmware-sadmin.iso"
          controller_number: 1
          unit_number: 0
        hardware:
          boot_firmware: "bios"
          memory_mb: 32768
          num_cpus: 8
          num_cpu_cores_per_socket: 4
          cpu_reservation: 16000
          mem_reservation: 32768
          memory_reservation_lock: true
          scsi: paravirtual
          version: latest
        validate_certs: no
      delegate_to: localhost
      register: deploy_vm
      ignore_errors: yes

    - name: Power on virtual machine
      community.vmware.vmware_guest_powerstate:
        validate_certs: false
        name: vmware-sadmin
        state: powered-on

    - name: Your ISE nodes have been deployed!
      ansible.builtin.debug:
        msg: |
          {{bar}}(@@,     g@@@@g,g@@@@g,g@@@@g  @k     g@      @F g@@%%@g,   @L,g@@  ,g@NNBw  
          {{bar}} $@@    g@@P`@@@P``]@@@P``]@@@ '@C   ,@]@    #@         $K  @@P    @P     '@w 
          {{bar}}  $@@  g@@P  @@@    @@@    @@@  ]@   @` ]@  /@   gg%NN%m@@  @$    ]@ggggggg#@   
          {{bar}}   $@@g@@P   @@@    @@@    @@@   ]@ @F   $k,@`  @F      [@  @F    ]@            
          {{bar}}    $@@@P    @@@    @@@    @@@    $@@     @@F   %@,   ,g$@  @F     "$g,  ,g@    
          {{bar}}     ""`      "`    `"`    '"`     "       `      """"  '`  "         """"  
          {{bar}}
          {{bar}}           Your ISE nodes have been deployed on VMware ESXi!
          {{bar}}
          {{bar}} - {{ upg_ppan }} 
          {{bar}} - {{ upg_span }}
    - name: Refresh inventory to ensure new instances exist in inventory ⟳
      ansible.builtin.meta: refresh_inventory
