---
- name: Wait for ISE login to be available (Application Server)
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

  tasks:

    - name: Wait for ISE App Server on Primary Admin Node to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait ~25 minutes for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on vmware-admin
            (::::)
           --------

    - name: ISE Login ⮕ | vmware-admin
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://vmware-admin.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks

    - name: Wait for ISE App Server on Secondary Admin Node to Come Up ∆ ∆ ∆
      ansible.builtin.debug:
        msg: |
           
           ________
            (    )
             \../
              )(     Wait for ISE AppServer to Come Up ∆ ∆ ∆
             /  \    on vmware-sadmin
            (::::)
           --------

    - name: ISE Login ⮕ | vmware-sadmin
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://vmware-sadmin.securitydemo.net/admin/login.jsp
        method: GET
        follow_redirects: safe
        timeout: "3"
        validate_certs: "no"
        return_content: no
      register: result
      until: result.status == 200
      retries: "1000"
      delay: "10" # wait between checks