---
- name: Pause for services
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../vars/main.yaml
    - ../vars/banners.yaml

  tasks:
   
  - name: 🛑 Pause for 60 seconds to for command to finish 🛑
    ansible.builtin.pause:
      seconds: 60
