---
- name: The first Iteration of Cloud PSN Upgrades is Complete!
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../../vars/main.yaml
    - ../../vars/banners.yaml

  tasks:

    - name: Send Email Notification
      ansible.builtin.shell:
        cmd: "ssmtp charlie@isedemolab.com < ../../notifications/33_iteration1_done.txt"

    - name: Iteration 1 is Complete!! 🤍
      ansible.builtin.debug:
        msg: |
           
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣶
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣯⣿
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣯⣯⣯⣿
           ⠀⠀⠀⠀⠀⠀⠀⢀⣤⡶⠀⠀⠀⢠⣿⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⢴⣤
           ⠀⠀⠀⠀⠀⢀⣴⠟⠀⠀⠀⠀⢠⣿⣯⣯⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⠈⢻⣦
           ⠀⠀⠀⠀⢠⣿⠁⠀⠀⠀⠀⢀⣿⣯⣯⣯⣯⣯⣯⣯⣯⣯⣿⠀⠀⠀⠀⠀⠈⣿⡀
           ⠀⠀⠀⢠⣿⠀⠀⠀⠀⠀⢀⣿⣯⣯⣯⣯⠟⠛⢿⣯⣯⣯⣯⣿⠀⠀⠀⠀⠀⠀⣿
           ⠀⠀⠀⣿⠁⠀⠀⠀⠀⢀⣿⣯⣯⠛⠁⠀⠀⠀⠀⠀⠉⠛⣿⣯⣿⠀⠀⠀⠀⠀⢸⣧  Iteration 1 complete!
           ⠀⠀⠀⣿⠀⠀⠀⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⣿
           ⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣶⠀⢀⣴⠶⠒⠶⣤⠀⠀⣶⠶⠶⠶⠶⠀⠀⠀⠀⠀⢀⣿  Move on to Iteration 2
           ⠀⠀⠀⢻⣆⠀⠀⠀⠀⠀⣿⠀⠘⣧⣀⠀⠀⠈⠁⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠏
           ⠀⠀⠀⠀⢿⣄⠀⠀⠀⠀⣿⠀⠀⠀⠀⠉⠙⢷⡀⠀⣿⠉⠉⠉⠉⠀⠀⠀⠀⣰⡟
           ⠀⠀⠀⠀⠀⢻⣦⠀⠀⠀⣿⠀⠙⣦⣀⣀⣀⣼⠁⠀⣿⣀⣀⣀⣀⠀⠀⠀⣼⠋
           ⠀⠀⠀⠀⠀⠀⠈⢿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⠟⠉
           ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠛⠛⠛⠋⠉⠁
           
           
        