---
- name: Remove nodes from ISE deployment
  ansible.builtin.import_playbook: 01-remove_nodes.yaml

- name: Delete aws-psn (ISE 3.2)
  ansible.builtin.import_playbook: 04-delete_aws_psn.yaml

- name: Create aws-psn (ISE 3.3)
  ansible.builtin.import_playbook: 07-create_aws_33.yaml

- name: Delete azure-psn (ISE 3.2)
  ansible.builtin.import_playbook: 02-delete_azure_32.yaml

- name: Create azure-psn (ISE 3.3)
  ansible.builtin.import_playbook: 05-create_azure_33.yaml

- name: Delete oci-psn (ISE 3.2)
  ansible.builtin.import_playbook: 03-delete_oci_psn.yaml

- name: Create oci-psn (ISE 3.3)
  ansible.builtin.import_playbook: 06-create_oci_33.yaml

- name: Wait for Application Server to be available
  ansible.builtin.import_playbook: 08-wait_for_ise_login.yaml

# - name: Enable APIs
#   ansible.builtin.import_playbook: 09-enable_api.yaml

# - name: Configure FTP Repository
#   ansible.builtin.import_playbook: 10-create_ftp_repository.yaml

# - name: Install latest patch for ISE release
#   ansible.builtin.import_playbook: 11-patch_install.yaml

# - name: Wait for Application Server to be available
#   ansible.builtin.import_playbook: 08-wait_for_ise_login.yaml

- name: Add the PSNs into the 3.3 deployment
  ansible.builtin.import_playbook: 12-add_nodes.yaml

- name: Iteration 1 Complete!
  ansible.builtin.import_playbook: 13-Iteration_1_complete.yaml