---
# tasks file for roles/ise_env_ansible_valid

- name: Check Cache Status
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ cache_file }}"
  register: cache_file_status


# ansible_become_user # The user  This must be available to the ‘login user’.
# ansible_connection  
# ansible_host       
# ansible_python_interpreter
# ansible_user       
- name: Show Ansible Connection Variables
  delegate_to: localhost
  loop:
    - ansible_python_interpreter # path to the Python executable Ansible should use on the target host
    - ansible_connection         # Connection plugin actually used for the task on the target host
    - ansible_host               # IP/name of the target host to use instead of inventory_hostname
    - ansible_user               # user Ansible ‘logs in’ as
    - ansible_become_user        # Ansible ‘becomes’ after using privilege escalation
  ansible.builtin.debug:
    msg: "{{ item }}: {{ lookup('vars', item, default='UNDEFINED') }}"
    verbosity: 1

- name: Check ISE Environment Variables
  when: not cache_file_status.stat.exists or (( '%s' | strftime | int ) - ( cache_file_status.stat.mtime | int )) > cache_time
  block:
    - name: Check ISE Environment Variables
      delegate_to: localhost
      when: lookup('env', item) is undefined
      loop:
        - ISE_USERNAME
        - ISE_PASSWORD
        - ISE_RADIUS_SECRET
        - ISE_TACACS_SECRET
      ansible.builtin.fail:
        msg: |+
          ❌ Please set environment variable {{ item }}

          export {{ item }}=__________


    - name: Validate ISE Module Variables
      loop:
        - ise_username
        - ise_password
      ansible.builtin.fail:
      when: item is undefined

    - name: Validate Minimum cisco.ise Ansible Package
      delegate_to: localhost
      when: lookup('community.general.collection_version', 'cisco.ise') is version(cisco_ise_package_minimum, '<')
      ansible.builtin.fail:
        msg: ❌  Ansible package cisco.ise is < {{ cisco_ise_package_minimum }} ({{ lookup('community.general.collection_version', 'cisco.ise') }}

- name: Cache Environment Status with Hidden File
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ cache_file }}"
    state: touch
  when: not cache_file_status.stat.exists
    or
    (( '%s' | strftime | int ) - ( cache_file_status.stat.mtime | int )) > cache_time
#   register: touched
# - ansible.builtin.debug: var=touched.diff.after.mtime

