---
- name: Reset ISE GUI Password
  hosts: oci-psn
  connection: ansible.netcommon.network_cli
  gather_facts: false
    - ../../vars/main.yaml
    - ../../vars/banners.yaml
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_ssh_user: "{{ lookup('env','ISE_REST_USERNAME') }}"
    ansible_ssh_private_key_file: "{{ ssh_key_private_file }}.pub"
  vars_prompt:
    - name: username
      prompt: What is the username to reset?
      default: iseadmin
      private: no
    - name: new_password
      prompt: What is the new password?
      private: yes
  tasks:

    #--------------------------------------------------------------------------
    # 💡 ISE 3.2+ cloud instances use the superadmin account `iseadmin`
    #
    # 💡 ISE Application Server must be running to reset password!
    #
    # 💡 Possible errors:
    #    - Cannot reuse password within {{n}} days.
    # Example command output:
    #
    # ```
    # ise/iseadmin#application reset-passwd ise admin
    # Enter new password:
    # Confirm new password:
    #
    # Password reset successfully.
    # ```
    #--------------------------------------------------------------------------

    - name: GUI Password Reset | {{ username }}@{{ inventory_hostname }}
      ansible.netcommon.cli_command:
        command: "application reset-passwd ise {{ username }}"
        check_all: yes
        sendonly: no
        newline: yes
        prompt:
          - "Enter new password:"
          - "Confirm new password:"
        answer:
          - "{{ new_password }}"
          - "{{ new_password }}"
      register: output
      failed_when: "'successfully' not in output.stdout"

    - name: output.stdout
      when:
        - output is defined
        - output.stdout is defined
      ansible.builtin.debug:
        var: output.stdout
        # verbosity: 3

    - name: Exit | {{ inventory_hostname }}
      when: username == "admin"
      ansible.netcommon.cli_command:
        command: "exit"

    - name: Password Reset Successful
      ansible.builtin.debug:
        msg: |
                      ,•010101•,
                 ,•0101010''1010101•,
            ,•0101010'`         '1010110•,
            1010'`                   '0101
            010         ,•010,         010
            101        10`  `10        101
            010       |01     10       010
            101      •01010101010      101
            1101    |0101010101010    ,010     Password Change was Successful on {{ inventory_hostname }}
             010    |1010101010101    010`
             \101   |0101010101010   /100
              1101  |1010101010101  0101
               '010,              ,0101
                 \100,          ,0100
                   101010,  ,•01010
                      '010101010`
                          ``